pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - check-success=tests
      - author=Mic92
    actions:
      merge:
        method: merge
      delete_head_branch: {}
